#!/bin/bash

case "$1" in
	"log")	docker logs compose_bbsim_1 &> bbsim$2.log
	;;
	"flog")	docker logs -f compose_bbsim_1
	;;
	"exec")	docker exec -it compose_bbsim_1 sh
	;;
	*) echo "Invalid option for component compose_bbsim_1, log/flog/exec"
	;;
esac

