#!/bin/bash

case "$1" in
	"log")	docker logs compose_vconsul_1 &> consul$2.log
	;;
	"flog")	docker logs -f compose_vconsul_1
	;;
	"exec")	docker exec -it compose_vconsul_1 sh
	;;
	*) echo "Invalid option for component compose_vconsul_1, log/flog/exec"
	;;
esac
