#!/bin/bash

case "$1" in
	"log")	docker logs compose_etcd_1 &> etcd$2.log
	;;
	"flog")	docker logs -f compose_etcd_1
	;;
	"exec")	docker exec -it compose_etcd_1 sh
	;;
	*) echo "Invalid option for component compose_etcd_1, log/flog/exec"
	;;
esac
