#!/bin/bash

case "$1" in
	"log")	docker logs compose_kafka_1 &> kafka$2.log
	;;
	"flog")	docker logs -f compose_kafka_1
	;;
	"exec")	docker exec -it compose_kafka_1 sh
	;;
	*) echo "Invalid option for component compose_kafka_1, log/flog/exec"
	;;
esac
