#!/bin/bash

case "$1" in
	"log")	docker logs compose_rw_core_1 &> voltha$2.log
	;;
	"flog")	docker logs -f compose_rw_core_1
	;;
	"exec")	docker exec -it compose_rw_core_1 sh
	;;
	*) echo "Invalid option for component compose_rw_core_1, log/flog/exec"
	;;
esac
